### ISSUE TITLE
Error while trying to lemmatize(word)

### ISSUE THREAD

**Issue by bm777** [Rahil-17/Chatbot-for-Ecommerce-websites#1]
Hi @Rahil-17. I need your help.
I encountered an error while running the python file ner.py.

This is the error:

```
-> Camera of xiaomi redmi note 4s pro snapdargon samsing
camera {'camera', 'cameras'}
xiaomi {'xiaomi'}
redmi {'redmi'}
note {'note'}
4s {'os', '4s', 'xs', '4g'}
pro {'pro'}
snapdargon {'snapdragon'}
samsing {'samsung'}
query -:  ['Camera', '', 'xiaomi', 'redmi', 'note', '4s', 'pro', 'snapdragon', 'samsung']

result -:  Camera  xiaomi redmi note 4s pro snapdragon samsung
word :  {'camera', 'cameras'}
Traceback (most recent call last):
  File "ner.py", line 203, in <module>
    main()
  File "ner.py", line 197, in main
    process_NL(q5)
  File "ner.py", line 146, in process_NL
---------->  result = get_ner(s)
  File "ner.py", line 100, in get_ner
 ---------->  query = preprocess_query(query)
  File "ner.py", line 71, in preprocess_query
 ---------->  print(wordnet_lemmatizer.lemmatize(word))
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/stem/wordnet.py", line 38, in lemmatize
    lemmas = wordnet._morphy(word, pos)
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/corpus/util.py", line 120, in __getattr__
    self.__load()
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/corpus/util.py", line 80, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, self.__name))
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/data.py", line 557, in find
    return find(modified_name, paths)
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/data.py", line 544, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/data.py", line 396, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/bm7/.mars/tg/lib/python3.6/site-packages/nltk/data.py", line 936, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

I installed nltk 3.5 for python 3.6
ubuntu 18.04 OS

**Comment by bm777** [comment]
I solve this

**Comment by bm777** [comment]
I solve the problem using 

`nltk.download('wordnet')
`
![error](https://user-images.githubusercontent.com/29865600/89539873-389c9780-d7f4-11ea-8b77-7ecc4f4e190d.png)
